name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: iwd
    - name: CI
      if: github.event_name == 'pull_request'
      uses: IWDTestBot/action-ci@master
      with:
        src_path: iwd
        github_token: ${{ secrets.ACTION_TOKEN }}
        email_token: ${{ secrets.EMAIL_TOKEN }}
        patchwork_token : ${{ secrets.PATCHWORK_TOKEN }}
        config: https://raw.githubusercontent.com/IWDTestBot/iwd/workflow/.github/workflows/ci-config.ini
        email_message: https://raw.githubusercontent.com/IWDTestBot/iwd/workflow/.github/workflows/ci-email.txt

  report-pending:
    runs-on: ubuntu-latest
    steps:

    - name: Report pending
      if: github.event_name == 'pull_request'
      uses: IWDTestBot/action-patchwork@main
      with:
        user: 185529
        state: pending
        patchwork_token: ${{ secrets.PATCHWORK_TOKEN }}
        context: 'test-runner'
        description: 'Run Autotests'
        github_token: ${{ secrets.ACTION_TOKEN }}

  test-runner:
    needs: report-pending
    runs-on: ubuntu-latest
    outputs:
      configure: ${{ steps.test.outputs.configure_iwd }}
      build: ${{ steps.test.outputs.build_iwd }}
      unit: ${{ steps.test.outputs.unit_iwd }}
      test: ${{ steps.test.outputs.test_iwd }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: iwd
    - name: test-runner
      uses: IWDTestBot/test-runner@main
      id: test
      with:
        tests: all
        runner: uml
        kernel: 5.16

  report:
    needs: test-runner
    runs-on: ubuntu-latest
    steps:
    - name: Report Fail
      if: failure() && github.event_name == 'pull_request'
      uses: IWDTestBot/action-patchwork@main
      with:
        user: 185529
        state: fail
        patchwork_token: ${{ secrets.PATCHWORK_TOKEN }}
        context: 'test-runner'
        description: 'Run Autotests'
        github_token: ${{ secrets.ACTION_TOKEN }}

    - name: Report Success
      if: success() && github.event_name == 'pull_request'
      uses: IWDTestBot/action-patchwork@main
      with:
        user: 185529
        state: pass
        patchwork_token: ${{ secrets.PATCHWORK_TOKEN }}
        context: 'test-runner'
        description: 'Run Autotests'
        github_token: ${{ secrets.ACTION_TOKEN }}

    - name: Print Results
      if: always()
      run: |
        echo Configure: ${{ needs.test-runner.outputs.configure }}
        echo Build: ${{ needs.test-runner.outputs.build }}
        echo Unit: ${{ needs.test-runner.outputs.unit }}
        echo Test: ${{ needs.test-runner.outputs.test }}
