name: Test Runner
on:
  workflow_dispatch:
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu-latest
    steps:

    - name: Report Patchwork
      if: always()
      uses: IWDTestBot/action-patchwork@main
      with:
        user: 104215
        state: pending
        patchwork_token: ${{ secrets.PATCHWORK_TOKEN }}
        context: 'Test context'
        description: 'A test description'
        github_token: ${{ secrets.ACTION_TOKEN }}

    - uses: IWDTestBot/test-runner@main
      id: test
      with:
        tests: all
        runner: uml
        kernel: 5.16

    - name: Report Results
      if: always()
      run: |
        echo Configure: ${{ steps.test.outputs.configure_iwd }}
        echo Build: ${{ steps.test.outputs.build_iwd }}
        echo Unit: ${{ steps.test.outputs.unit_iwd }}
        echo Test: ${{ steps.test.outputs.test_iwd }}
