name: Test
on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: ubuntu-latest
    steps:

    - uses: IWDTestBot/test-runner@main
      with:
        tests: all
        runner: uml
        kernel: 5.16
