name: Test Runner
on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: ubuntu-latest
    steps:

    - name: Report pending
      if: github.event_name == 'pull_request'
      uses: IWDTestBot/action-patchwork@main
      with:
        user: 185529
        state: pending
        patchwork_token: ${{ secrets.PATCHWORK_TOKEN }}
        context: 'test-runner'
        description: 'Run Autotests'
        github_token: ${{ secrets.ACTION_TOKEN }}

    - uses: IWDTestBot/test-runner@main
      id: test
      with:
        tests: all
        runner: uml
        kernel: 5.16

    - name: Report Fail
      if: failure() && github.event_name == 'pull_request'
      uses: IWDTestBot/action-patchwork@main
      with:
        user: 185529
        state: fail
        patchwork_token: ${{ secrets.PATCHWORK_TOKEN }}
        context: 'test-runner'
        description: 'Run Autotests'
        github_token: ${{ secrets.ACTION_TOKEN }}

    - name: Report Success
      if: success() && github.event_name == 'pull_request'
      uses: IWDTestBot/action-patchwork@main
      with:
        user: 185529
        state: pass
        patchwork_token: ${{ secrets.PATCHWORK_TOKEN }}
        context: 'test-runner'
        description: 'Run Autotests'
        github_token: ${{ secrets.ACTION_TOKEN }}


    - name: Print Results
      if: always()
      run: |
        echo Configure: ${{ steps.test.outputs.configure_iwd }}
        echo Build: ${{ steps.test.outputs.build_iwd }}
        echo Unit: ${{ steps.test.outputs.unit_iwd }}
        echo Test: ${{ steps.test.outputs.test_iwd }}
